// First digit can be cuted by serial port (it is an error)
#define METHOD_GETVERSION 	105
#define METHOD_PROG_MODE_ON 	110
#define METHOD_PROG_MODE_OFF 	114
#define METHOD_TEST_SLAVE 	119
#define METHOD_RESETCYCLES 	120
#define METHOD_ONECOLOR 	138
#define METHOD_SETTIME 	142
#define METHOD_SETFADING 	146
#define METHOD_RESETSLAVEADDRESS 	150
#define METHOD_GETANALOGVALUE 	151
#define METHOD_GETVALUE 	155
#define METHOD_RESET_NEXT 	158
#define METHOD_RUN_NEXT 	162
#define METHOD_GET_Y_POS 	165
#define METHOD_SET_Y_POS 	166
#define METHOD_GET_Z_POS 	169
#define METHOD_SET_Z_POS 	170
#define METHOD_LIVE_OFF 	172
#define METHOD_LIVE_ANALOG 	174
#define METHOD_DRIVER_ENABLE 	181
#define METHOD_DRIVER_DISABLE 	186
#define METHOD_HERE_I_AM 	116
#define METHOD_SEND_PIN_VALUE 	118
#define METHOD_CAN_FILL 	126
#define METHOD_I2C_SLAVEMSG 	122
#define RETURN_DRIVER_ERROR 	180
#define RETURN_DRIVER_READY 	182
#define RETURN_DRIVER_READY_REPEAT 	184
#define RETURN_PIN_VALUE 	111
#define METHOD_STEPPER_MOVING 	123
#define METHOD_IMPORTANT_ANALOG 	125
#define METHOD_IMPORTANT_ANALOG_ERROR 	124
#define RETURN_I2C_ERROR 	153
#define METHOD_EXEC_ERROR 	133
#define METHOD_DEVICE_FOUND 	112
#define METHOD_SETLED 	140
#define METHOD_SET_TOP_COLOR 	148
#define METHOD_SET_BOTTOM_COLOR 	152
#define METHOD_SETLEDS 	144
#define METHOD_CHECK_NEXT 	188
#define METHOD_EEPROM_READ_I2C 	190
#define METHOD_EEPROM_WRITE_I2C 192
#define METHOD_GET_X_POS 	157


#define METHOD_SET_X_ACCELERATION 	"AX"
#define METHOD_MASTER_CAN_FILL 	'F'
#define METHOD_SET_X_DISABLE 	"DX"
#define METHOD_ERROR 	'E'
#define METHOD_SET_X_ENABLE 	"EX"
#define METHOD_POING 	"POING"
#define METHOD_PONG 	"PONG"
#define METHOD_PROG 	"PROG"
#define METHOD_PROGN 	"PROGN"
#define METHOD_RESET_BUS 	"RB"
#define METHOD_RESET 	"RESET"
#define METHOD_RWIRE 	"RWIRE"
#define METHOD_SEND2SLAVE 	'S'
#define METHOD_TRIGGER 		'T'
#define METHOD_M_ONECOLOR 	'B'
#define METHOD_WAIT_READY 	"WR"
#define METHOD_SET_X_POS 	'X'
#define METHOD_GET_TEMP 	'T'
#define METHOD_MSET_LED 	'L'
// set top color
#define METHOD_MSET_TOP_COLOR 	'C'
// set bottom color
#define METHOD_MSET_BOTTOM_COLOR 	'c'
#define METHOD_HAS_NEXT 	'N'
#define METHOD_SLAVE_HAS_NEXT 	'n'
#define METHOD_EEPROM_READ 	'M'
#define METHOD_EEPROM_WRITE 'S'


//24 * 2^0  + 252* 2^1 + 255* 2^2 + 255* 2^3

// typy b³êdów:
#define T_UNKNOWN_E		0x05
#define T_ENGINE_E		0x06
#define T_WRITE_I2C_E	0x07	
#define T_READ_I2C_E	0x08



// inne
#define DRIVER_DIR_FORWARD 	32
#define DRIVER_DIR_BACKWARD 64
#define DRIVER_DIR_STOP		0

#define INNER_SERVOY  0
#define INNER_SERVOZ  1

#define DRIVER_X 	4
#define DRIVER_Y 	8
#define DRIVER_Z 	16

#define INNER_HALL_X 0
#define INNER_HALL_Y 1
#define INNER_WEIGHT 2
#define INNER_CURRENTY 3
#define INNER_CURRENTZ 4
#define INNER_TABLET 5
#define INNER_MB_TEMP 6
#define INNER_CARRET_TEMP 7


#define HX_STATE_0		11
#define HX_STATE_1		22
#define HX_STATE_2		33
#define HX_STATE_3		44
#define HX_STATE_4		55

#define HX_STATE_5		66

#define HX_STATE_6		77
#define HX_STATE_7		88
#define HX_STATE_8		99
#define HX_STATE_9		100
#define HX_STATE_10		111



#define HX_SPEED  35

// HALL X VALUES 
#define HX_NEODYM_UP_BELOW  750
#define HX_NEODYM_UP_START  600
#define HX_FERRITE_UP_IS_BELOW  560
#define HX_LOCAL_UP_MAX_OVER  540

#define HX_NOISE_BELOW 531
#define HX_NOISE_OVER  518

#define HX_LOCAL_DOWN_IS_BELOW  513
#define HX_FERRITE_DOWN_IS_BELOW  495
#define HX_NEODYM_DOWN_START  450
#define HX_NEODYM_DOWN_OVER  300

// end HALL X VALUES 



