#define METHOD_GETVERSION 	5
#define METHOD_PROG_MODE_ON 	10
#define METHOD_PROG_MODE_OFF 	14
#define METHOD_TEST_SLAVE 	19
#define METHOD_RESETCYCLES 	20
#define METHOD_SETPWM 	38
#define METHOD_SETTIME 	42
#define METHOD_SETFADING 	46
#define METHOD_RESETSLAVEADDRESS 	50
#define METHOD_GETANALOGVALUE 	51
#define METHOD_GETVALUE 	55
#define METHOD_RESET_NEXT 	58
#define METHOD_RUN_NEXT 	62
#define METHOD_GET_Y_POS 	65
#define METHOD_SET_Y_POS 	66
#define METHOD_GET_Z_POS 	69
#define METHOD_SET_Z_POS 	70
#define METHOD_LIVE_OFF 	72
#define METHOD_LIVE_ANALOG 	74
#define METHOD_DRIVER_ENABLE 	82
#define METHOD_DRIVER_DISABLE 	86
#define METHOD_HERE_I_AM 	114
#define METHOD_SEND_PIN_VALUE 	118
#define METHOD_CAN_FILL 	120
#define METHOD_I2C_SLAVEMSG 	122
#define RETURN_DRIVER_ERROR 	180
#define RETURN_DRIVER_READY 	182
#define RETURN_PIN_VALUE 	211
#define METHOD_STEPPER_MOVING 	222
#define METHOD_IMPORTANT_ANALOG 	224
#define RETURN_I2C_ERROR 	53
#define METHOD_EXEC_ERROR 	22
#define METHOD_DEVICE_FOUND 	12
#define METHOD_SETLED 	40
#define METHOD_SETLEDS 	44

#define METHOD_SET_X_ACCELERATION 	"AX"
#define METHOD_MASTER_CAN_FILL 	"CF"
#define METHOD_SET_X_DISABLE 	"DX"
#define METHOD_ERROR 	'E'
#define METHOD_SET_X_ENABLE 	"EX"
#define METHOD_GET_X_POS 	"GPX"
#define METHOD_POING 	"POING"
#define METHOD_PONG 	"PONG"
#define METHOD_PROG 	"PROG"
#define METHOD_PROGN 	"PROGN"
#define METHOD_RESET_BUS 	"RB"
#define METHOD_RESET 	"RESET"
#define METHOD_RWIRE 	"RWIRE"
#define METHOD_SEND2SLAVE 	'S'
#define METHOD_TRIGGER 	'T'
#define METHOD_WAIT_READY 	"WR"
#define METHOD_SET_X_POS 	'X'
#define METHOD_GET_TEMP 	'T'
#define METHOD_MSET_LED 	'L'





//24 * 2^0  + 252* 2^1 + 255* 2^2 + 255* 2^3

// typy b³êdów:
#define 	T_UNKNOWN_E		0x05
#define 	T_ENGINE_E		0x06
#define 	T_WRITE_I2C_E	0x07	
#define 	T_READ_I2C_E	0x08



// inne
#define DRIVER_DIR_FORWARD 	32
#define DRIVER_DIR_BACKWARD 64
#define DRIVER_DIR_STOP		0

#define INNER_SERVOY  0
#define INNER_SERVOZ  1

#define DRIVER_X 	4
#define DRIVER_Y 	8
#define DRIVER_Z 	16

#define INNER_HALL_X 0
#define INNER_HALL_Y 0
#define INNER_WEIGHT 1

#define HALL_GLOBAL_MIN 1
#define HALL_GLOBAL_MAX 2
#define HALL_LOCAL_MAX 4
#define HALL_LOCAL_MIN 8
